version: "3.8"

services:

    web:
        image: nginx:latest
        volumes:
            - ./:/usr/share/nginx/html
        ports:
            - "80:80"
    db:
        image: mysql:latest # use latest version of mysql
        container_name: db # add a name for the container
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./db:/var/lib/mysql
        expose:
            - '3306:3306'
        depends_on:
            - "web"

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8082:80
        depends_on:
            - "db"
